# Colors

foreground #93a4c3 
background #21283b 

color0 #0c0e15
color1 #f65866
color2 #8bcd5b
color3 #efbd5d
color4 #41a7fc
color5 #c75ae8
color6 #34bfd0
color7 #979eab
color8 #393e48
color9 #992525
color10 #56b6c2
color11 #8f610d
color12 #61afef
color13 #862aa1
color14 #1b6a73
color15 #abb2bf
#
# Tab Bar

active_tab_foreground   #393e48
active_tab_background   #41a7fc
inactive_tab_foreground #41a7fc
inactive_tab_background #393e48
